-- Generated from src/data/products.js. Run after 001_initial_schema.sql.

insert into public.products (
  id,
  name,
  category,
  sub_category,
  channels,
  packaging,
  pack_size,
  price,
  reseller_price,
  slab_price,
  kg_per_box,
  brand,
  stock,
  featured,
  home_retail_featured,
  home_wholesale_featured,
  promo,
  description,
  sort_order
)
values
(
  'retail-chicken-leg-quarter-pack-per-kg',
  'CHICKEN Leg Quarter',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  225,
  215,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  0
),
(
  'retail-chicken-wings-pack-per-kg',
  'CHICKEN Wings',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  245,
  235,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  1
),
(
  'retail-chicken-breast-fillet-pack-per-kg',
  'CHICKEN Breast Fillet',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  270,
  260,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  2
),
(
  'retail-magnolia-whole-chicken-pack-per-kg',
  'Magnolia Whole Chicken',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  235,
  230,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  3
),
(
  'retail-chicken-liver-pack-per-kg',
  'Chicken Liver',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  215,
  205,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  4
),
(
  'retail-chickengizzard-balunan-pack-per-kg',
  'ChickenGizzard (Balunan)',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  160,
  150,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  5
),
(
  'retail-vibra-whole-chicken-griller-pack-per-kg',
  'Vibra Whole Chicken Griller',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  220,
  210,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  6
),
(
  'retail-dressed-whole-chicken-pack-per-kg',
  'Dressed Whole Chicken',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  188,
  178,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  7
),
(
  'retail-dressed-half-chicken-pack-per-kg',
  'Dressed Half Chicken',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  188,
  188,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  8
),
(
  'retail-pork-laman-pack-per-kg',
  'PORK Laman',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  270,
  260,
  240,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  9
),
(
  'retail-pork-liempo-pack-per-kg',
  'PORK Liempo',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  360,
  350,
  300,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  10
),
(
  'retail-pork-chop-pack-per-kg',
  'PORK Chop',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  280,
  270,
  260,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  11
),
(
  'retail-pork-spare-ribs-pack-per-kg',
  'PORK Spare Ribs',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  300,
  290,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  12
),
(
  'retail-pork-riblets-buto-buto-pack-per-kg',
  'PORK Riblets (Buto-Buto)',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  240,
  230,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  13
),
(
  'retail-pork-liver-pack-per-kg',
  'PORK Liver',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  160,
  150,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  14
),
(
  'retail-pork-jowl-pack-per-kg',
  'PORK Jowl',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  250,
  240,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  15
),
(
  'retail-pork-ear-pack-per-kg',
  'PORK Ear',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  200,
  190,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  16
),
(
  'retail-pork-mask-pack-per-kg',
  'PORK Mask',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  185,
  175,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  17
),
(
  'retail-pork-hock-pata-whole-sliced-pack-per-kg',
  'PORK Hock/Pata (Whole&Sliced)',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  250,
  240,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  18
),
(
  'retail-pork-samgyeopsal-1-kg',
  'PORK Samgyeopsal',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  400,
  390,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Pork product packed as 1 Kg.',
  19
),
(
  'retail-ground-pork-1-kg',
  'GROUND Pork',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  280,
  135,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as 1 Kg.',
  20
),
(
  'retail-ground-pork-500g',
  'GROUND Pork',
  'Frozen',
  'Pork',
  array['retail']::text[],
  '500g',
  '500g',
  145,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as 500g.',
  21
),
(
  'retail-flower-fat-chicharong-bulaklak-pack-per-kg',
  'Flower Fat (Chicharong Bulaklak)',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  185,
  175,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  22
),
(
  'retail-beef-laman-forequarter-pack-per-kg',
  'Beef Laman (Forequarter)',
  'Frozen',
  'Beef',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  410,
  400,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Beef product packed as Pack per Kg.',
  23
),
(
  'retail-beef-shank-bulalo-cut-pack-per-kg',
  'Beef Shank (Bulalo Cut)',
  'Frozen',
  'Beef',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  400,
  390,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Beef product packed as Pack per Kg.',
  24
),
(
  'retail-ground-beef-1-kg',
  'Ground Beef',
  'Frozen',
  'Beef',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  420,
  205,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Beef product packed as 1 Kg.',
  25
),
(
  'retail-ground-beef-500g',
  'Ground Beef',
  'Frozen',
  'Beef',
  array['retail']::text[],
  '500g',
  '500g',
  215,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Beef product packed as 500g.',
  26
),
(
  'retail-beef-samgyeopsal-1-kg',
  'Beef Samgyeopsal',
  'Frozen',
  'Beef',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  440,
  430,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Beef product packed as 1 Kg.',
  27
),
(
  'retail-brazilian-ribeye-steak-pack',
  'Brazilian Ribeye Steak',
  'Frozen',
  'Steak',
  array['retail', 'reseller']::text[],
  'Pack',
  'Pack',
  980,
  950,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Steak product packed as Pack.',
  28
),
(
  'retail-tomahawk-steak-usda-choice-pack-per-kg',
  'Tomahawk Steak (USDA Choice)',
  'Frozen',
  'Steak',
  array['retail']::text[],
  'Pack per Kg',
  'Pack per Kg',
  2300,
  null,
  null,
  null,
  null,
  'out-of-stock',
  false,
  true,
  false,
  'Out of stock',
  'Frozen Steak product packed as Pack per Kg.',
  29
),
(
  'retail-kuchidoke-wagyu-cubes-1-kg',
  'Kuchidoke Wagyu Cubes',
  'Frozen',
  'Steak',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  1350,
  1300,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Steak product packed as 1 Kg.',
  30
),
(
  'retail-maestro-chicken-dumplings-920g',
  'Maestro Chicken Dumplings',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '920g',
  '920g',
  260,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 920g.',
  31
),
(
  'retail-maestro-chicken-breast-nuggets-1-kg',
  'Maestro Chicken Breast Nuggets',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '1 Kg',
  '1 Kg',
  370,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  32
),
(
  'retail-maestro-chicken-popcorn-1-kg',
  'Maestro Chicken Popcorn',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '1 Kg',
  '1 Kg',
  375,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  33
),
(
  'retail-bossing-hungarian-sausage-500g',
  'Bossing Hungarian sausage',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '500g',
  '500g',
  165,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 500g.',
  34
),
(
  'retail-tender-juicy-hotdog-classic-1-kg',
  'Tender Juicy Hotdog Classic',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '1 Kg',
  '1 Kg',
  210,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  35
),
(
  'retail-tender-juicy-hotdog-jumbo-1-kg',
  'Tender Juicy Hotdog Jumbo',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '1 Kg',
  '1 Kg',
  215,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  36
),
(
  'retail-tender-juicy-chicken-cheese-hotdog-1-kg',
  'Tender Juicy Chicken & Cheese Hotdog',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '1 Kg',
  '1 Kg',
  220,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  37
),
(
  'retail-purefoods-breast-nuggets-135g',
  'PureFoods Breast Nuggets',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '135g',
  '135g',
  69,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 135g.',
  38
),
(
  'retail-home-made-longanisa-500g',
  'Home Made Longanisa',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '500g',
  '500g',
  170,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 500g.',
  39
),
(
  'retail-home-made-skinless-longanisa-500g',
  'Home Made Skinless Longanisa',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '500g',
  '500g',
  170,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 500g.',
  40
),
(
  'retail-cdo-sweet-ham-250g',
  'CDO Sweet Ham',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '250g',
  '250g',
  95,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 250g.',
  41
),
(
  'retail-cdo-beef-tapa-250g',
  'CDO Beef Tapa',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '250g',
  '250g',
  115,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 250g.',
  42
),
(
  'retail-cdo-funtastyk-tocino-225g',
  'CDO Funtastyk Tocino',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '225g',
  '225g',
  76,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 225g.',
  43
),
(
  'retail-maestro-shabu-shabu-balls-260g',
  'Maestro Shabu-Shabu Balls',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '260g',
  '260g',
  110,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 260g.',
  44
),
(
  'retail-maestro-crabstick-200g',
  'Maestro Crabstick',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '200g',
  '200g',
  70,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 200g.',
  45
),
(
  'retail-maestro-mixed-vegetables-1kg',
  'Maestro Mixed Vegetables',
  'Frozen',
  'Processed Food',
  array['retail', 'reseller']::text[],
  '1kg',
  '1kg',
  115,
  110,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1kg.',
  46
),
(
  'retail-hansung-korean-luncheon-meat-piece',
  'Hansung Korean Luncheon Meat',
  'Grocery',
  'Food',
  array['retail', 'reseller']::text[],
  'Piece',
  'Piece',
  115,
  105,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Food product packed as Piece.',
  47
),
(
  'retail-namkwang-seaweed-nori-3-pieces',
  'Namkwang Seaweed Nori',
  'Grocery',
  'Food',
  array['retail']::text[],
  '3 Pieces',
  '3 Pieces',
  55,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Food product packed as 3 Pieces.',
  48
),
(
  'retail-namkwang-seaweed-nori-piece',
  'Namkwang Seaweed Nori',
  'Grocery',
  'Food',
  array['retail']::text[],
  'Piece',
  'Piece',
  20,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Food product packed as Piece.',
  49
),
(
  'retail-jin-ramen-mild-piece',
  'Jin Ramen Mild',
  'Grocery',
  'Food',
  array['retail']::text[],
  'Piece',
  'Piece',
  50,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Food product packed as Piece.',
  50
),
(
  'retail-jin-ramen-mild-pack-of-5-pack',
  'Jin Ramen Mild Pack of 5',
  'Grocery',
  'Food',
  array['retail']::text[],
  'Pack',
  'Pack',
  225,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Food product packed as Pack.',
  51
),
(
  'retail-o-food-mild-ssamjang-170g',
  'O'' Food Mild Ssamjang',
  'Grocery',
  'Condiment',
  array['retail']::text[],
  '170g',
  '170g',
  85,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Condiment product packed as 170g.',
  52
),
(
  'retail-cj-gochujang-170g',
  'CJ Gochujang',
  'Grocery',
  'Condiment',
  array['retail']::text[],
  '170g',
  '170g',
  95,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Condiment product packed as 170g.',
  53
),
(
  'retail-egg-tray-large-tray',
  'Egg Tray- Large',
  'Fresh',
  'Food',
  array['retail']::text[],
  'Tray',
  'Tray',
  280,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Fresh Food product packed as Tray.',
  54
),
(
  'retail-egg-piece',
  'Egg',
  'Fresh',
  'Food',
  array['retail']::text[],
  'Piece',
  'Piece',
  10,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Fresh Food product packed as Piece.',
  55
),
(
  'retail-pork-siomain-big-20-pieces',
  'Pork Siomain BIG',
  'Frozen',
  'Processed Food',
  array['retail', 'reseller']::text[],
  '20 Pieces',
  '20 Pieces',
  170,
  160,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 20 Pieces.',
  56
),
(
  'retail-french-fries-1-kg',
  'French Fries',
  'Frozen',
  'Processed Food',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  135,
  130,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  57
),
(
  'retail-palm-oil-1-liter',
  'Palm Oil',
  'Grocery',
  'Condiment',
  array['retail']::text[],
  '1 Liter',
  '1 Liter',
  120,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Condiment product packed as 1 Liter.',
  58
),
(
  'wholesale-chicken-leg-quarter-tyson',
  'Chicken Leg Quarter (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '15kg',
  165,
  null,
  null,
  '15kg',
  'TYSON',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from TYSON. Minimum order is 1 box.',
  59
),
(
  'wholesale-chicken-leg-quarter-lamex-georges',
  'Chicken Leg Quarter (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '15kg',
  160,
  null,
  null,
  '15kg',
  'LAMEX/GEORGES',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from LAMEX/GEORGES. Minimum order is 1 box.',
  60
),
(
  'wholesale-chicken-thigh-quarter-perdue-carolina-fare',
  'Chicken Thigh Quarter (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '15kg',
  150,
  null,
  null,
  '15kg',
  'PERDUE/CAROLINA FARE',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from PERDUE/CAROLINA FARE. Minimum order is 1 box.',
  61
),
(
  'wholesale-chicken-breast-fillet-sadia',
  'Chicken Breast Fillet (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '7.5kg-15kg',
  231,
  null,
  null,
  '7.5kg-15kg',
  'SADIA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from SADIA. Minimum order is 1 box.',
  62
),
(
  'wholesale-chicken-whole-leg-fillet-perdigao',
  'Chicken Whole Leg Fillet (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '12kg',
  225,
  null,
  null,
  '12kg',
  'PERDIGAO',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from PERDIGAO. Minimum order is 1 box.',
  63
),
(
  'wholesale-chicken-wings-3-joints-perdigao',
  'Chicken Wings 3 Joints (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '15kg',
  168,
  null,
  null,
  '15kg',
  'PERDIGAO',
  'in-stock',
  false,
  false,
  true,
  'Fast moving',
  'Wholesale Chicken box from PERDIGAO. Minimum order is 1 box.',
  64
),
(
  'wholesale-whole-chicken-organic-vibra-nat',
  'Whole Chicken (Organic) (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  200,
  null,
  null,
  '10kg',
  'VIBRA/NAT',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from VIBRA/NAT. Minimum order is 1 box.',
  65
),
(
  'wholesale-chicken-fat-sadia',
  'Chicken Fat (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  96,
  null,
  null,
  '10kg',
  'SADIA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from SADIA. Minimum order is 1 box.',
  66
),
(
  'wholesale-whole-chicken-organic-nat-vibra',
  'Whole Chicken (Organic) (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  200,
  null,
  null,
  '10kg',
  'NAT VIBRA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from NAT VIBRA. Minimum order is 1 box.',
  67
),
(
  'wholesale-pork-picnic-shoulder-kasim-seara',
  'Pork Picnic Shoulder (KASIM) (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '18kg-23kg',
  210,
  null,
  null,
  '18kg-23kg',
  'SEARA',
  'in-stock',
  false,
  false,
  true,
  'Fast moving',
  'Wholesale Pork box from SEARA. Minimum order is 1 box.',
  68
),
(
  'wholesale-pork-belly-biso-montagne',
  'Pork Belly BISO (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '18kg-23kg',
  270,
  null,
  null,
  '18kg-23kg',
  'MONTAGNE',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from MONTAGNE. Minimum order is 1 box.',
  69
),
(
  'wholesale-porkloin-bisl-seara',
  'Porkloin BISL (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '18kg-23kg',
  196,
  null,
  null,
  '18kg-23kg',
  'SEARA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from SEARA. Minimum order is 1 box.',
  70
),
(
  'wholesale-pork-spareribs-sadia',
  'Pork Spareribs (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '18kg',
  264,
  null,
  null,
  '18kg',
  'SADIA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from SADIA. Minimum order is 1 box.',
  71
),
(
  'wholesale-pork-pata-front-whole-conestoga',
  'Pork Pata Front Whole (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '18kg',
  184,
  null,
  null,
  '18kg',
  'CONESTOGA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from CONESTOGA. Minimum order is 1 box.',
  72
),
(
  'wholesale-pork-jowls-danish-crown',
  'Pork Jowls (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '10kg-25kg',
  204,
  null,
  null,
  '10kg-25kg',
  'DANISH CROWN',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from DANISH CROWN. Minimum order is 1 box.',
  73
),
(
  'wholesale-pork-jowls-sadia',
  'Pork Jowls (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '10kg-21kg',
  200,
  null,
  null,
  '10kg-21kg',
  'SADIA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from SADIA. Minimum order is 1 box.',
  74
),
(
  'wholesale-pork-liver-pilgrims',
  'Pork Liver (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  127,
  null,
  null,
  '10kg',
  'PILGRIMS',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from PILGRIMS. Minimum order is 1 box.',
  75
),
(
  'wholesale-pork-mask-w-out-snout-ear-seara',
  'Pork Mask w/ out Snout/Ear (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  151,
  null,
  null,
  '10kg',
  'SEARA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from SEARA. Minimum order is 1 box.',
  76
),
(
  'wholesale-pork-flower-fat-chicharong-bulaklak-ecofrigo',
  'Pork Flower Fat (Chicharong Bulaklak) (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  116,
  null,
  null,
  '10kg',
  'ECOFRIGO',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from ECOFRIGO. Minimum order is 1 box.',
  77
),
(
  'wholesale-pork-flower-fat-chicharong-bulaklak-famadesa',
  'Pork Flower Fat (Chicharong Bulaklak) (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '20kg-25kg',
  116,
  null,
  null,
  '20kg-25kg',
  'FAMADESA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from FAMADESA. Minimum order is 1 box.',
  78
),
(
  'wholesale-beef-forequarter-golden-imex',
  'Beef Forequarter (Box)',
  'Frozen',
  'Beef',
  array['wholesale']::text[],
  'BOX',
  '19kg-25kg',
  356,
  null,
  null,
  '19kg-25kg',
  'GOLDEN IMEX',
  'in-stock',
  false,
  false,
  true,
  'Fast moving',
  'Wholesale Beef box from GOLDEN IMEX. Minimum order is 1 box.',
  79
),
(
  'wholesale-french-fries-mc-cain-shoe-string-fries',
  'French Fries (Box)',
  'Frozen',
  'Processed Food',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  115,
  null,
  null,
  '10kg',
  'MC CAIN SHOE STRING FRIES',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Processed Food box from MC CAIN SHOE STRING FRIES. Minimum order is 1 box.',
  80
),
(
  'wholesale-french-fries-maestro-shoe-string-fries',
  'French Fries (Box)',
  'Frozen',
  'Processed Food',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  115,
  null,
  null,
  '10kg',
  'MAESTRO SHOE STRING FRIES',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Processed Food box from MAESTRO SHOE STRING FRIES. Minimum order is 1 box.',
  81
)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  sub_category = excluded.sub_category,
  channels = excluded.channels,
  packaging = excluded.packaging,
  pack_size = excluded.pack_size,
  price = excluded.price,
  reseller_price = excluded.reseller_price,
  slab_price = excluded.slab_price,
  kg_per_box = excluded.kg_per_box,
  brand = excluded.brand,
  stock = excluded.stock,
  featured = excluded.featured,
  home_retail_featured = excluded.home_retail_featured,
  home_wholesale_featured = excluded.home_wholesale_featured,
  promo = excluded.promo,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();
