-- Product seed chunk 01. Run after 001_initial_schema.sql.

insert into public.products (
  id,
  name,
  category,
  sub_category,
  channels,
  packaging,
  pack_size,
  price,
  reseller_price,
  slab_price,
  kg_per_box,
  brand,
  stock,
  featured,
  home_retail_featured,
  home_wholesale_featured,
  promo,
  description,
  sort_order
)
values
(
  'retail-chicken-leg-quarter-pack-per-kg',
  'CHICKEN Leg Quarter',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  225,
  215,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  0
),
(
  'retail-chicken-wings-pack-per-kg',
  'CHICKEN Wings',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  245,
  235,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  1
),
(
  'retail-chicken-breast-fillet-pack-per-kg',
  'CHICKEN Breast Fillet',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  270,
  260,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  2
),
(
  'retail-magnolia-whole-chicken-pack-per-kg',
  'Magnolia Whole Chicken',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  235,
  230,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  3
),
(
  'retail-chicken-liver-pack-per-kg',
  'Chicken Liver',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  215,
  205,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  4
),
(
  'retail-chickengizzard-balunan-pack-per-kg',
  'ChickenGizzard (Balunan)',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  160,
  150,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  5
),
(
  'retail-vibra-whole-chicken-griller-pack-per-kg',
  'Vibra Whole Chicken Griller',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  220,
  210,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  6
),
(
  'retail-dressed-whole-chicken-pack-per-kg',
  'Dressed Whole Chicken',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  188,
  178,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  7
),
(
  'retail-dressed-half-chicken-pack-per-kg',
  'Dressed Half Chicken',
  'Frozen',
  'Chicken',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  188,
  188,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Chicken product packed as Pack per Kg.',
  8
),
(
  'retail-pork-laman-pack-per-kg',
  'PORK Laman',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  270,
  260,
  240,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  9
),
(
  'retail-pork-liempo-pack-per-kg',
  'PORK Liempo',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  360,
  350,
  300,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  10
),
(
  'retail-pork-chop-pack-per-kg',
  'PORK Chop',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  280,
  270,
  260,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  11
),
(
  'retail-pork-spare-ribs-pack-per-kg',
  'PORK Spare Ribs',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  300,
  290,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  12
),
(
  'retail-pork-riblets-buto-buto-pack-per-kg',
  'PORK Riblets (Buto-Buto)',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  240,
  230,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  13
),
(
  'retail-pork-liver-pack-per-kg',
  'PORK Liver',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  160,
  150,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  14
),
(
  'retail-pork-jowl-pack-per-kg',
  'PORK Jowl',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  250,
  240,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  15
),
(
  'retail-pork-ear-pack-per-kg',
  'PORK Ear',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  200,
  190,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  16
),
(
  'retail-pork-mask-pack-per-kg',
  'PORK Mask',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  185,
  175,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  17
),
(
  'retail-pork-hock-pata-whole-sliced-pack-per-kg',
  'PORK Hock/Pata (Whole&Sliced)',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  250,
  240,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  18
),
(
  'retail-pork-samgyeopsal-1-kg',
  'PORK Samgyeopsal',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  400,
  390,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Pork product packed as 1 Kg.',
  19
)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  sub_category = excluded.sub_category,
  channels = excluded.channels,
  packaging = excluded.packaging,
  pack_size = excluded.pack_size,
  price = excluded.price,
  reseller_price = excluded.reseller_price,
  slab_price = excluded.slab_price,
  kg_per_box = excluded.kg_per_box,
  brand = excluded.brand,
  stock = excluded.stock,
  featured = excluded.featured,
  home_retail_featured = excluded.home_retail_featured,
  home_wholesale_featured = excluded.home_wholesale_featured,
  promo = excluded.promo,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();
