-- Product seed chunk 02. Run after 001_initial_schema.sql.

insert into public.products (
  id,
  name,
  category,
  sub_category,
  channels,
  packaging,
  pack_size,
  price,
  reseller_price,
  slab_price,
  kg_per_box,
  brand,
  stock,
  featured,
  home_retail_featured,
  home_wholesale_featured,
  promo,
  description,
  sort_order
)
values
(
  'retail-ground-pork-1-kg',
  'GROUND Pork',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  280,
  135,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as 1 Kg.',
  20
),
(
  'retail-ground-pork-500g',
  'GROUND Pork',
  'Frozen',
  'Pork',
  array['retail']::text[],
  '500g',
  '500g',
  145,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as 500g.',
  21
),
(
  'retail-flower-fat-chicharong-bulaklak-pack-per-kg',
  'Flower Fat (Chicharong Bulaklak)',
  'Frozen',
  'Pork',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  185,
  175,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Pork product packed as Pack per Kg.',
  22
),
(
  'retail-beef-laman-forequarter-pack-per-kg',
  'Beef Laman (Forequarter)',
  'Frozen',
  'Beef',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  410,
  400,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Beef product packed as Pack per Kg.',
  23
),
(
  'retail-beef-shank-bulalo-cut-pack-per-kg',
  'Beef Shank (Bulalo Cut)',
  'Frozen',
  'Beef',
  array['retail', 'reseller']::text[],
  'Pack per Kg',
  'Pack per Kg',
  400,
  390,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Beef product packed as Pack per Kg.',
  24
),
(
  'retail-ground-beef-1-kg',
  'Ground Beef',
  'Frozen',
  'Beef',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  420,
  205,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Beef product packed as 1 Kg.',
  25
),
(
  'retail-ground-beef-500g',
  'Ground Beef',
  'Frozen',
  'Beef',
  array['retail']::text[],
  '500g',
  '500g',
  215,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Beef product packed as 500g.',
  26
),
(
  'retail-beef-samgyeopsal-1-kg',
  'Beef Samgyeopsal',
  'Frozen',
  'Beef',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  440,
  430,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Beef product packed as 1 Kg.',
  27
),
(
  'retail-brazilian-ribeye-steak-pack',
  'Brazilian Ribeye Steak',
  'Frozen',
  'Steak',
  array['retail', 'reseller']::text[],
  'Pack',
  'Pack',
  980,
  950,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Steak product packed as Pack.',
  28
),
(
  'retail-tomahawk-steak-usda-choice-pack-per-kg',
  'Tomahawk Steak (USDA Choice)',
  'Frozen',
  'Steak',
  array['retail']::text[],
  'Pack per Kg',
  'Pack per Kg',
  2300,
  null,
  null,
  null,
  null,
  'out-of-stock',
  false,
  true,
  false,
  'Out of stock',
  'Frozen Steak product packed as Pack per Kg.',
  29
),
(
  'retail-kuchidoke-wagyu-cubes-1-kg',
  'Kuchidoke Wagyu Cubes',
  'Frozen',
  'Steak',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  1350,
  1300,
  null,
  null,
  null,
  'in-stock',
  false,
  true,
  false,
  null,
  'Frozen Steak product packed as 1 Kg.',
  30
),
(
  'retail-maestro-chicken-dumplings-920g',
  'Maestro Chicken Dumplings',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '920g',
  '920g',
  260,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 920g.',
  31
),
(
  'retail-maestro-chicken-breast-nuggets-1-kg',
  'Maestro Chicken Breast Nuggets',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '1 Kg',
  '1 Kg',
  370,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  32
),
(
  'retail-maestro-chicken-popcorn-1-kg',
  'Maestro Chicken Popcorn',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '1 Kg',
  '1 Kg',
  375,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  33
),
(
  'retail-bossing-hungarian-sausage-500g',
  'Bossing Hungarian sausage',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '500g',
  '500g',
  165,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 500g.',
  34
),
(
  'retail-tender-juicy-hotdog-classic-1-kg',
  'Tender Juicy Hotdog Classic',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '1 Kg',
  '1 Kg',
  210,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  35
),
(
  'retail-tender-juicy-hotdog-jumbo-1-kg',
  'Tender Juicy Hotdog Jumbo',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '1 Kg',
  '1 Kg',
  215,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  36
),
(
  'retail-tender-juicy-chicken-cheese-hotdog-1-kg',
  'Tender Juicy Chicken & Cheese Hotdog',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '1 Kg',
  '1 Kg',
  220,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  37
),
(
  'retail-purefoods-breast-nuggets-135g',
  'PureFoods Breast Nuggets',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '135g',
  '135g',
  69,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 135g.',
  38
),
(
  'retail-home-made-longanisa-500g',
  'Home Made Longanisa',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '500g',
  '500g',
  170,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 500g.',
  39
)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  sub_category = excluded.sub_category,
  channels = excluded.channels,
  packaging = excluded.packaging,
  pack_size = excluded.pack_size,
  price = excluded.price,
  reseller_price = excluded.reseller_price,
  slab_price = excluded.slab_price,
  kg_per_box = excluded.kg_per_box,
  brand = excluded.brand,
  stock = excluded.stock,
  featured = excluded.featured,
  home_retail_featured = excluded.home_retail_featured,
  home_wholesale_featured = excluded.home_wholesale_featured,
  promo = excluded.promo,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();
