-- Product seed chunk 03. Run after 001_initial_schema.sql.

insert into public.products (
  id,
  name,
  category,
  sub_category,
  channels,
  packaging,
  pack_size,
  price,
  reseller_price,
  slab_price,
  kg_per_box,
  brand,
  stock,
  featured,
  home_retail_featured,
  home_wholesale_featured,
  promo,
  description,
  sort_order
)
values
(
  'retail-home-made-skinless-longanisa-500g',
  'Home Made Skinless Longanisa',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '500g',
  '500g',
  170,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 500g.',
  40
),
(
  'retail-cdo-sweet-ham-250g',
  'CDO Sweet Ham',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '250g',
  '250g',
  95,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 250g.',
  41
),
(
  'retail-cdo-beef-tapa-250g',
  'CDO Beef Tapa',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '250g',
  '250g',
  115,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 250g.',
  42
),
(
  'retail-cdo-funtastyk-tocino-225g',
  'CDO Funtastyk Tocino',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '225g',
  '225g',
  76,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 225g.',
  43
),
(
  'retail-maestro-shabu-shabu-balls-260g',
  'Maestro Shabu-Shabu Balls',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '260g',
  '260g',
  110,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 260g.',
  44
),
(
  'retail-maestro-crabstick-200g',
  'Maestro Crabstick',
  'Frozen',
  'Processed Food',
  array['retail']::text[],
  '200g',
  '200g',
  70,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 200g.',
  45
),
(
  'retail-maestro-mixed-vegetables-1kg',
  'Maestro Mixed Vegetables',
  'Frozen',
  'Processed Food',
  array['retail', 'reseller']::text[],
  '1kg',
  '1kg',
  115,
  110,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1kg.',
  46
),
(
  'retail-hansung-korean-luncheon-meat-piece',
  'Hansung Korean Luncheon Meat',
  'Grocery',
  'Food',
  array['retail', 'reseller']::text[],
  'Piece',
  'Piece',
  115,
  105,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Food product packed as Piece.',
  47
),
(
  'retail-namkwang-seaweed-nori-3-pieces',
  'Namkwang Seaweed Nori',
  'Grocery',
  'Food',
  array['retail']::text[],
  '3 Pieces',
  '3 Pieces',
  55,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Food product packed as 3 Pieces.',
  48
),
(
  'retail-namkwang-seaweed-nori-piece',
  'Namkwang Seaweed Nori',
  'Grocery',
  'Food',
  array['retail']::text[],
  'Piece',
  'Piece',
  20,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Food product packed as Piece.',
  49
),
(
  'retail-jin-ramen-mild-piece',
  'Jin Ramen Mild',
  'Grocery',
  'Food',
  array['retail']::text[],
  'Piece',
  'Piece',
  50,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Food product packed as Piece.',
  50
),
(
  'retail-jin-ramen-mild-pack-of-5-pack',
  'Jin Ramen Mild Pack of 5',
  'Grocery',
  'Food',
  array['retail']::text[],
  'Pack',
  'Pack',
  225,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Food product packed as Pack.',
  51
),
(
  'retail-o-food-mild-ssamjang-170g',
  'O'' Food Mild Ssamjang',
  'Grocery',
  'Condiment',
  array['retail']::text[],
  '170g',
  '170g',
  85,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Condiment product packed as 170g.',
  52
),
(
  'retail-cj-gochujang-170g',
  'CJ Gochujang',
  'Grocery',
  'Condiment',
  array['retail']::text[],
  '170g',
  '170g',
  95,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Condiment product packed as 170g.',
  53
),
(
  'retail-egg-tray-large-tray',
  'Egg Tray- Large',
  'Fresh',
  'Food',
  array['retail']::text[],
  'Tray',
  'Tray',
  280,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Fresh Food product packed as Tray.',
  54
),
(
  'retail-egg-piece',
  'Egg',
  'Fresh',
  'Food',
  array['retail']::text[],
  'Piece',
  'Piece',
  10,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Fresh Food product packed as Piece.',
  55
),
(
  'retail-pork-siomain-big-20-pieces',
  'Pork Siomain BIG',
  'Frozen',
  'Processed Food',
  array['retail', 'reseller']::text[],
  '20 Pieces',
  '20 Pieces',
  170,
  160,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 20 Pieces.',
  56
),
(
  'retail-french-fries-1-kg',
  'French Fries',
  'Frozen',
  'Processed Food',
  array['retail', 'reseller']::text[],
  '1 Kg',
  '1 Kg',
  135,
  130,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Frozen Processed Food product packed as 1 Kg.',
  57
),
(
  'retail-palm-oil-1-liter',
  'Palm Oil',
  'Grocery',
  'Condiment',
  array['retail']::text[],
  '1 Liter',
  '1 Liter',
  120,
  null,
  null,
  null,
  null,
  'in-stock',
  false,
  false,
  false,
  null,
  'Grocery Condiment product packed as 1 Liter.',
  58
),
(
  'wholesale-chicken-leg-quarter-tyson',
  'Chicken Leg Quarter (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '15kg',
  165,
  null,
  null,
  '15kg',
  'TYSON',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from TYSON. Minimum order is 1 box.',
  59
)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  sub_category = excluded.sub_category,
  channels = excluded.channels,
  packaging = excluded.packaging,
  pack_size = excluded.pack_size,
  price = excluded.price,
  reseller_price = excluded.reseller_price,
  slab_price = excluded.slab_price,
  kg_per_box = excluded.kg_per_box,
  brand = excluded.brand,
  stock = excluded.stock,
  featured = excluded.featured,
  home_retail_featured = excluded.home_retail_featured,
  home_wholesale_featured = excluded.home_wholesale_featured,
  promo = excluded.promo,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();
