-- Product seed chunk 04. Run after 001_initial_schema.sql.

insert into public.products (
  id,
  name,
  category,
  sub_category,
  channels,
  packaging,
  pack_size,
  price,
  reseller_price,
  slab_price,
  kg_per_box,
  brand,
  stock,
  featured,
  home_retail_featured,
  home_wholesale_featured,
  promo,
  description,
  sort_order
)
values
(
  'wholesale-chicken-leg-quarter-lamex-georges',
  'Chicken Leg Quarter (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '15kg',
  160,
  null,
  null,
  '15kg',
  'LAMEX/GEORGES',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from LAMEX/GEORGES. Minimum order is 1 box.',
  60
),
(
  'wholesale-chicken-thigh-quarter-perdue-carolina-fare',
  'Chicken Thigh Quarter (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '15kg',
  150,
  null,
  null,
  '15kg',
  'PERDUE/CAROLINA FARE',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from PERDUE/CAROLINA FARE. Minimum order is 1 box.',
  61
),
(
  'wholesale-chicken-breast-fillet-sadia',
  'Chicken Breast Fillet (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '7.5kg-15kg',
  231,
  null,
  null,
  '7.5kg-15kg',
  'SADIA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from SADIA. Minimum order is 1 box.',
  62
),
(
  'wholesale-chicken-whole-leg-fillet-perdigao',
  'Chicken Whole Leg Fillet (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '12kg',
  225,
  null,
  null,
  '12kg',
  'PERDIGAO',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from PERDIGAO. Minimum order is 1 box.',
  63
),
(
  'wholesale-chicken-wings-3-joints-perdigao',
  'Chicken Wings 3 Joints (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '15kg',
  168,
  null,
  null,
  '15kg',
  'PERDIGAO',
  'in-stock',
  false,
  false,
  true,
  'Fast moving',
  'Wholesale Chicken box from PERDIGAO. Minimum order is 1 box.',
  64
),
(
  'wholesale-whole-chicken-organic-vibra-nat',
  'Whole Chicken (Organic) (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  200,
  null,
  null,
  '10kg',
  'VIBRA/NAT',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from VIBRA/NAT. Minimum order is 1 box.',
  65
),
(
  'wholesale-chicken-fat-sadia',
  'Chicken Fat (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  96,
  null,
  null,
  '10kg',
  'SADIA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from SADIA. Minimum order is 1 box.',
  66
),
(
  'wholesale-whole-chicken-organic-nat-vibra',
  'Whole Chicken (Organic) (Box)',
  'Frozen',
  'Chicken',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  200,
  null,
  null,
  '10kg',
  'NAT VIBRA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Chicken box from NAT VIBRA. Minimum order is 1 box.',
  67
),
(
  'wholesale-pork-picnic-shoulder-kasim-seara',
  'Pork Picnic Shoulder (KASIM) (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '18kg-23kg',
  210,
  null,
  null,
  '18kg-23kg',
  'SEARA',
  'in-stock',
  false,
  false,
  true,
  'Fast moving',
  'Wholesale Pork box from SEARA. Minimum order is 1 box.',
  68
),
(
  'wholesale-pork-belly-biso-montagne',
  'Pork Belly BISO (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '18kg-23kg',
  270,
  null,
  null,
  '18kg-23kg',
  'MONTAGNE',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from MONTAGNE. Minimum order is 1 box.',
  69
),
(
  'wholesale-porkloin-bisl-seara',
  'Porkloin BISL (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '18kg-23kg',
  196,
  null,
  null,
  '18kg-23kg',
  'SEARA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from SEARA. Minimum order is 1 box.',
  70
),
(
  'wholesale-pork-spareribs-sadia',
  'Pork Spareribs (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '18kg',
  264,
  null,
  null,
  '18kg',
  'SADIA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from SADIA. Minimum order is 1 box.',
  71
),
(
  'wholesale-pork-pata-front-whole-conestoga',
  'Pork Pata Front Whole (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '18kg',
  184,
  null,
  null,
  '18kg',
  'CONESTOGA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from CONESTOGA. Minimum order is 1 box.',
  72
),
(
  'wholesale-pork-jowls-danish-crown',
  'Pork Jowls (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '10kg-25kg',
  204,
  null,
  null,
  '10kg-25kg',
  'DANISH CROWN',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from DANISH CROWN. Minimum order is 1 box.',
  73
),
(
  'wholesale-pork-jowls-sadia',
  'Pork Jowls (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '10kg-21kg',
  200,
  null,
  null,
  '10kg-21kg',
  'SADIA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from SADIA. Minimum order is 1 box.',
  74
),
(
  'wholesale-pork-liver-pilgrims',
  'Pork Liver (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  127,
  null,
  null,
  '10kg',
  'PILGRIMS',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from PILGRIMS. Minimum order is 1 box.',
  75
),
(
  'wholesale-pork-mask-w-out-snout-ear-seara',
  'Pork Mask w/ out Snout/Ear (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  151,
  null,
  null,
  '10kg',
  'SEARA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from SEARA. Minimum order is 1 box.',
  76
),
(
  'wholesale-pork-flower-fat-chicharong-bulaklak-ecofrigo',
  'Pork Flower Fat (Chicharong Bulaklak) (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  116,
  null,
  null,
  '10kg',
  'ECOFRIGO',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from ECOFRIGO. Minimum order is 1 box.',
  77
),
(
  'wholesale-pork-flower-fat-chicharong-bulaklak-famadesa',
  'Pork Flower Fat (Chicharong Bulaklak) (Box)',
  'Frozen',
  'Pork',
  array['wholesale']::text[],
  'BOX',
  '20kg-25kg',
  116,
  null,
  null,
  '20kg-25kg',
  'FAMADESA',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Pork box from FAMADESA. Minimum order is 1 box.',
  78
),
(
  'wholesale-beef-forequarter-golden-imex',
  'Beef Forequarter (Box)',
  'Frozen',
  'Beef',
  array['wholesale']::text[],
  'BOX',
  '19kg-25kg',
  356,
  null,
  null,
  '19kg-25kg',
  'GOLDEN IMEX',
  'in-stock',
  false,
  false,
  true,
  'Fast moving',
  'Wholesale Beef box from GOLDEN IMEX. Minimum order is 1 box.',
  79
)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  sub_category = excluded.sub_category,
  channels = excluded.channels,
  packaging = excluded.packaging,
  pack_size = excluded.pack_size,
  price = excluded.price,
  reseller_price = excluded.reseller_price,
  slab_price = excluded.slab_price,
  kg_per_box = excluded.kg_per_box,
  brand = excluded.brand,
  stock = excluded.stock,
  featured = excluded.featured,
  home_retail_featured = excluded.home_retail_featured,
  home_wholesale_featured = excluded.home_wholesale_featured,
  promo = excluded.promo,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();
