-- Product seed chunk 05. Run after 001_initial_schema.sql.

insert into public.products (
  id,
  name,
  category,
  sub_category,
  channels,
  packaging,
  pack_size,
  price,
  reseller_price,
  slab_price,
  kg_per_box,
  brand,
  stock,
  featured,
  home_retail_featured,
  home_wholesale_featured,
  promo,
  description,
  sort_order
)
values
(
  'wholesale-french-fries-mc-cain-shoe-string-fries',
  'French Fries (Box)',
  'Frozen',
  'Processed Food',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  115,
  null,
  null,
  '10kg',
  'MC CAIN SHOE STRING FRIES',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Processed Food box from MC CAIN SHOE STRING FRIES. Minimum order is 1 box.',
  80
),
(
  'wholesale-french-fries-maestro-shoe-string-fries',
  'French Fries (Box)',
  'Frozen',
  'Processed Food',
  array['wholesale']::text[],
  'BOX',
  '10kg',
  115,
  null,
  null,
  '10kg',
  'MAESTRO SHOE STRING FRIES',
  'in-stock',
  false,
  false,
  false,
  null,
  'Wholesale Processed Food box from MAESTRO SHOE STRING FRIES. Minimum order is 1 box.',
  81
)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  sub_category = excluded.sub_category,
  channels = excluded.channels,
  packaging = excluded.packaging,
  pack_size = excluded.pack_size,
  price = excluded.price,
  reseller_price = excluded.reseller_price,
  slab_price = excluded.slab_price,
  kg_per_box = excluded.kg_per_box,
  brand = excluded.brand,
  stock = excluded.stock,
  featured = excluded.featured,
  home_retail_featured = excluded.home_retail_featured,
  home_wholesale_featured = excluded.home_wholesale_featured,
  promo = excluded.promo,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();
